/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.gking.view;

import br.com.gking.controller.database;
import br.com.gking.model.Veiculo;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gking
 */
public class gerenciar_veiculos extends javax.swing.JFrame {
    private static Veiculo veiculo;

    /**
     * Creates new form gerenciar_clientes
     * 
     * @param veiculo
     */
    public gerenciar_veiculos(Veiculo veiculo) {
        initComponents();
        this.veiculo = veiculo;
        this.placaText.setText(veiculo.getPlaca());
        this.marcaText.setText(veiculo.getMarca());
        this.modeloText.setText(veiculo.getModelo());
        this.anoText.setText(Integer.toString(veiculo.getAno()));
        this.corText.setText(veiculo.getCor());
        this.quilometragemText.setText(Integer.toString(veiculo.getQuilometragem()));
        this.categoriaText.setText(veiculo.getCategoria());
        this.disponibilidadeBotao.setSelected(veiculo.isDisponibilidade());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        placaText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        marcaText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        modeloText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        anoText = new javax.swing.JTextField();
        editarBotao = new javax.swing.JButton();
        excluirBotao = new javax.swing.JToggleButton();
        salvarBotao = new javax.swing.JToggleButton();
        cadastrarBotao = new javax.swing.JToggleButton();
        corText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        quilometragemText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        categoriaText = new javax.swing.JTextField();
        disponibilidadeBotao = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        voltarBotao = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 119, 37));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Placa");

        placaText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        placaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaTextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Marca:");

        marcaText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        marcaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaTextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modelo:");

        modeloText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        modeloText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ano:");

        anoText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        anoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoTextActionPerformed(evt);
            }
        });

        editarBotao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        editarBotao.setForeground(new java.awt.Color(141, 60, 14));
        editarBotao.setText("Editar");
        editarBotao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBotaoActionPerformed(evt);
            }
        });

        excluirBotao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        excluirBotao.setForeground(new java.awt.Color(141, 60, 14));
        excluirBotao.setText("Excluir");
        excluirBotao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        excluirBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBotaoActionPerformed(evt);
            }
        });

        salvarBotao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        salvarBotao.setForeground(new java.awt.Color(141, 60, 14));
        salvarBotao.setText("Salvar");
        salvarBotao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salvarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBotaoActionPerformed(evt);
            }
        });

        cadastrarBotao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cadastrarBotao.setForeground(new java.awt.Color(141, 60, 14));
        cadastrarBotao.setText("Cadastrar");
        cadastrarBotao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cadastrarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBotaoActionPerformed(evt);
            }
        });

        corText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        corText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cor");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Disponibilidade");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quilometragem");

        quilometragemText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        quilometragemText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quilometragemTextActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Categoria");

        categoriaText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        categoriaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaTextActionPerformed(evt);
            }
        });

        disponibilidadeBotao.setBorder(null);
        disponibilidadeBotao.setMaximumSize(new java.awt.Dimension(23, 23));
        disponibilidadeBotao.setMinimumSize(new java.awt.Dimension(23, 23));
        disponibilidadeBotao.setPreferredSize(new java.awt.Dimension(23, 23));
        disponibilidadeBotao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                disponibilidadeBotaoItemStateChanged(evt);
            }
        });
        disponibilidadeBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disponibilidadeBotaoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        voltarBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        voltarBotao.setAlignmentY(0.0F);
        voltarBotao.setBorder(null);
        voltarBotao.setContentAreaFilled(false);
        voltarBotao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarBotao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        voltarBotao.setIconTextGap(0);
        voltarBotao.setMargin(new java.awt.Insets(0, 0, 0, 0));
        voltarBotao.setPreferredSize(new java.awt.Dimension(41, 37));
        voltarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBotaoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Gerenciamento de Veículos");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redcardelta.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(voltarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(voltarBotao, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disponibilidadeBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quilometragemText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriaText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modeloText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marcaText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(placaText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(editarBotao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(excluirBotao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salvarBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(anoText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadastrarBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(placaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(marcaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(modeloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(anoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(corText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(quilometragemText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(categoriaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(disponibilidadeBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarBotao)
                    .addComponent(excluirBotao)
                    .addComponent(salvarBotao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarBotao)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placaTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_placaTextActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_placaTextActionPerformed

    private void marcaTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_marcaTextActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_marcaTextActionPerformed

    private void modeloTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_modeloTextActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_modeloTextActionPerformed

    private void anoTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_anoTextActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_anoTextActionPerformed

    private void excluirBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_excluirBotaoActionPerformed
        var deletarSucesso = database.deletarVeiculo(veiculo.getPlaca());
        if (!deletarSucesso) {
            JOptionPane.showMessageDialog(rootPane, "Veículo deletado!");
            var telaInicialScreen = new tela_inicial();

            telaInicialScreen.show();
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro ao deletar veículo!");
        }
    }// GEN-LAST:event_excluirBotaoActionPerformed

    private void salvarBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salvarBotaoActionPerformed
        try {
            veiculo.setPlaca(placaText.getText());
            veiculo.setMarca(marcaText.getText());
            veiculo.setModelo(modeloText.getText());
            veiculo.setAno(Integer.parseInt(anoText.getText()));
            veiculo.setCor(corText.getText());
            veiculo.setQuilometragem(Integer.parseInt(quilometragemText.getText()));
            veiculo.setCategoria(categoriaText.getText());
            veiculo.setDisponibilidade(disponibilidadeBotao.isSelected());

            var atualizarSucesso = database.atualizarVeiculo(veiculo.getPlaca(), veiculo);

            if (!atualizarSucesso) {
                JOptionPane.showMessageDialog(rootPane, "Veículo atualizado!");
                modoConsulta();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao deletar veículo!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(gerenciar_veiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_salvarBotaoActionPerformed

    private void editarBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editarBotaoActionPerformed
        // TODO add your handling code here:
        modoEdicao();
    }// GEN-LAST:event_editarBotaoActionPerformed

    private void cadastrarBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cadastrarBotaoActionPerformed
        try {
            veiculo.setPlaca(placaText.getText());
            veiculo.setMarca(marcaText.getText());
            veiculo.setModelo(modeloText.getText());
            veiculo.setAno(Integer.parseInt(anoText.getText()));
            veiculo.setCor(corText.getText());
            veiculo.setQuilometragem(Integer.parseInt(quilometragemText.getText()));
            veiculo.setCategoria(categoriaText.getText());
            veiculo.setDisponibilidade(disponibilidadeBotao.isSelected());

            var cadastroSucesso = database.cadastrarVeiculo(veiculo);

            if (!cadastroSucesso) {
                JOptionPane.showMessageDialog(rootPane, "Veículo cadastrado!");
                modoConsulta();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar veículo!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(gerenciar_veiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_cadastrarBotaoActionPerformed

    private void corTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_corTextActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_corTextActionPerformed

    private void quilometragemTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_quilometragemTextActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_quilometragemTextActionPerformed

    private void categoriaTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_categoriaTextActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_categoriaTextActionPerformed

    private void disponibilidadeBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_disponibilidadeBotaoActionPerformed

    }// GEN-LAST:event_disponibilidadeBotaoActionPerformed

    private void disponibilidadeBotaoItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_disponibilidadeBotaoItemStateChanged
        if (disponibilidadeBotao.isSelected()) {
            disponibilidadeBotao.setBackground(Color.green);
        } else {
            disponibilidadeBotao.setBackground(Color.red);
        }
    }// GEN-LAST:event_disponibilidadeBotaoItemStateChanged

    private void voltarBotaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_voltarBotaoActionPerformed
        var buscarVeiculosScreen = new buscar_placa();

        buscarVeiculosScreen.show();
        dispose();
    }// GEN-LAST:event_voltarBotaoActionPerformed

    private void voltarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBotaoActionPerformed
        var telaInicialScreen = new tela_inicial();

        telaInicialScreen.show();
        dispose();
    }//GEN-LAST:event_voltarBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gerenciar_veiculos.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gerenciar_veiculos.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gerenciar_veiculos.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gerenciar_veiculos.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new gerenciar_veiculos(veiculo).setVisible(true);
        });
    }

    public void modoConsulta() {
        placaText.setEnabled(false);
        marcaText.setEnabled(false);
        modeloText.setEnabled(false);
        anoText.setEnabled(false);
        corText.setEnabled(false);
        quilometragemText.setEnabled(false);
        categoriaText.setEnabled(false);
        disponibilidadeBotao.setEnabled(false);

        excluirBotao.setVisible(false);
        editarBotao.setVisible(true);
        salvarBotao.setVisible(false);
        cadastrarBotao.setVisible(false);

        disponibilidadeBotao.setSelected(veiculo.isDisponibilidade());
    }

    public void modoCadastro() {
        placaText.setEnabled(false);
        marcaText.setEnabled(true);
        modeloText.setEnabled(true);
        anoText.setEnabled(true);
        corText.setEnabled(true);
        quilometragemText.setEnabled(true);
        categoriaText.setEnabled(true);
        disponibilidadeBotao.setEnabled(true);

        excluirBotao.setVisible(false);
        editarBotao.setVisible(false);
        salvarBotao.setVisible(false);
        cadastrarBotao.setVisible(true);

        anoText.setText("");
        quilometragemText.setText("");
        disponibilidadeBotao.setSelected(true);
    }

    public void modoEdicao() {
        placaText.setEnabled(false);
        marcaText.setEnabled(true);
        modeloText.setEnabled(true);
        anoText.setEnabled(true);
        corText.setEnabled(true);
        quilometragemText.setEnabled(true);
        categoriaText.setEnabled(true);
        disponibilidadeBotao.setEnabled(true);

        excluirBotao.setVisible(true);
        editarBotao.setVisible(false);
        salvarBotao.setVisible(true);
        cadastrarBotao.setVisible(false);

        disponibilidadeBotao.setSelected(veiculo.isDisponibilidade());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoText;
    private javax.swing.JToggleButton cadastrarBotao;
    private javax.swing.JTextField categoriaText;
    private javax.swing.JTextField corText;
    private javax.swing.JToggleButton disponibilidadeBotao;
    private javax.swing.JButton editarBotao;
    private javax.swing.JToggleButton excluirBotao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField marcaText;
    private javax.swing.JTextField modeloText;
    private javax.swing.JTextField placaText;
    private javax.swing.JTextField quilometragemText;
    private javax.swing.JToggleButton salvarBotao;
    private javax.swing.JButton voltarBotao;
    // End of variables declaration//GEN-END:variables

}