/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.gking.view;

import br.com.gking.controller.database;
import br.com.gking.model.Veiculo;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gking
 */
public class gerenciar_veiculos extends javax.swing.JFrame {
    private static Veiculo veiculo;
    /**
     * Creates new form gerenciar_clientes
     * 
     * @param veiculo
     */
    public gerenciar_veiculos(Veiculo veiculo) {
        initComponents();
        this.veiculo = veiculo;
        this.placaText.setText(veiculo.getPlaca());
        this.marcaText.setText(veiculo.getMarca());
        this.modeloText.setText(veiculo.getModelo());
        this.anoText.setText(Integer.toString(veiculo.getAno()));
        this.corText.setText(veiculo.getCor());
        this.quilometragemText.setText(Integer.toString(veiculo.getQuilometragem()));
        this.categoriaText.setText(veiculo.getCategoria());
        this.disponibilidadeBotao.setSelected(veiculo.isDisponibilidade());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        placaText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        marcaText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        modeloText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        anoText = new javax.swing.JTextField();
        editarBotao = new javax.swing.JButton();
        excluirBotao = new javax.swing.JToggleButton();
        salvarBotao = new javax.swing.JToggleButton();
        cadastrarBotao = new javax.swing.JToggleButton();
        corText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        quilometragemText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        categoriaText = new javax.swing.JTextField();
        disponibilidadeBotao = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Placa");

        placaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca:");

        marcaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Modelo:");

        modeloText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Ano:");

        anoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoTextActionPerformed(evt);
            }
        });

        editarBotao.setText("Editar");
        editarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBotaoActionPerformed(evt);
            }
        });

        excluirBotao.setText("Excluir");
        excluirBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBotaoActionPerformed(evt);
            }
        });

        salvarBotao.setText("Salvar");
        salvarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBotaoActionPerformed(evt);
            }
        });

        cadastrarBotao.setText("Cadastrar");
        cadastrarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBotaoActionPerformed(evt);
            }
        });

        corText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corTextActionPerformed(evt);
            }
        });

        jLabel5.setText("Cor");

        jLabel6.setText("Disponibilidade");

        jLabel7.setText("Quilometragem");

        quilometragemText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quilometragemTextActionPerformed(evt);
            }
        });

        jLabel8.setText("Categoria");

        categoriaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaTextActionPerformed(evt);
            }
        });

        disponibilidadeBotao.setBorder(null);
        disponibilidadeBotao.setMaximumSize(new java.awt.Dimension(23, 23));
        disponibilidadeBotao.setMinimumSize(new java.awt.Dimension(23, 23));
        disponibilidadeBotao.setPreferredSize(new java.awt.Dimension(23, 23));
        disponibilidadeBotao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                disponibilidadeBotaoItemStateChanged(evt);
            }
        });
        disponibilidadeBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disponibilidadeBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disponibilidadeBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quilometragemText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriaText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modeloText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marcaText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(placaText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(editarBotao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(excluirBotao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salvarBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(anoText, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadastrarBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(placaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(marcaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(modeloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(anoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(corText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(quilometragemText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(categoriaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(disponibilidadeBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarBotao)
                    .addComponent(excluirBotao)
                    .addComponent(salvarBotao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarBotao)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_placaTextActionPerformed

    private void marcaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaTextActionPerformed

    private void modeloTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloTextActionPerformed

    private void anoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoTextActionPerformed

    private void excluirBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBotaoActionPerformed
        var deletarSucesso = database.deletarVeiculo(veiculo.getPlaca());
        if(!deletarSucesso){
            JOptionPane.showMessageDialog(rootPane, "Veículo deletado!");
            var telaInicialScreen = new tela_inicial();
            
            telaInicialScreen.show();
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro ao deletar veículo!");
        }
    }//GEN-LAST:event_excluirBotaoActionPerformed

    private void salvarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBotaoActionPerformed
        try {
            veiculo.setPlaca(placaText.getText());
            veiculo.setMarca(marcaText.getText());
            veiculo.setModelo(modeloText.getText());
            veiculo.setAno(Integer.parseInt(anoText.getText()));
            veiculo.setCor(corText.getText());
            veiculo.setQuilometragem(Integer.parseInt(quilometragemText.getText()));
            veiculo.setCategoria(categoriaText.getText());
            veiculo.setDisponibilidade(disponibilidadeBotao.isSelected());
            
            var atualizarSucesso = database.atualizarVeiculo(veiculo.getPlaca(), veiculo);
            
            if(!atualizarSucesso){
                JOptionPane.showMessageDialog(rootPane, "Veículo atualizado!");
                modoConsulta();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao deletar veículo!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(gerenciar_veiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_salvarBotaoActionPerformed

    private void editarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBotaoActionPerformed
        // TODO add your handling code here:
        modoEdicao();
    }//GEN-LAST:event_editarBotaoActionPerformed

    private void cadastrarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBotaoActionPerformed
        try {
            veiculo.setPlaca(placaText.getText());
            veiculo.setMarca(marcaText.getText());
            veiculo.setModelo(modeloText.getText());
            veiculo.setAno(Integer.parseInt(anoText.getText()));
            veiculo.setCor(corText.getText());
            veiculo.setQuilometragem(Integer.parseInt(quilometragemText.getText()));
            veiculo.setCategoria(categoriaText.getText());
            veiculo.setDisponibilidade(disponibilidadeBotao.isSelected());
            
            var cadastroSucesso = database.cadastrarVeiculo(veiculo);
            
            if(!cadastroSucesso){
                JOptionPane.showMessageDialog(rootPane, "Veículo cadastrado!");
                modoConsulta();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar veículo!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(gerenciar_veiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cadastrarBotaoActionPerformed

    private void corTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corTextActionPerformed

    private void quilometragemTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quilometragemTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quilometragemTextActionPerformed

    private void categoriaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaTextActionPerformed

    private void disponibilidadeBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disponibilidadeBotaoActionPerformed
        
    }//GEN-LAST:event_disponibilidadeBotaoActionPerformed

    private void disponibilidadeBotaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_disponibilidadeBotaoItemStateChanged
        if(disponibilidadeBotao.isSelected()){
            disponibilidadeBotao.setBackground(Color.green);
        } else {
            disponibilidadeBotao.setBackground(Color.red);
        }
    }//GEN-LAST:event_disponibilidadeBotaoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gerenciar_veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gerenciar_veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gerenciar_veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gerenciar_veiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new gerenciar_veiculos(veiculo).setVisible(true);
        });
    }
    
    public void modoConsulta(){
        placaText.setEnabled(false);
        marcaText.setEnabled(false);
        modeloText.setEnabled(false);
        anoText.setEnabled(false);
        corText.setEnabled(false);
        quilometragemText.setEnabled(false);
        categoriaText.setEnabled(false);
        disponibilidadeBotao.setEnabled(false);

        excluirBotao.setVisible(false);
        editarBotao.setVisible(true);
        salvarBotao.setVisible(false);
        cadastrarBotao.setVisible(false);
        
        disponibilidadeBotao.setSelected(veiculo.isDisponibilidade());
    }
    
    public void modoCadastro(){
        placaText.setEnabled(false);
        marcaText.setEnabled(true);
        modeloText.setEnabled(true);
        anoText.setEnabled(true);
        corText.setEnabled(true);
        quilometragemText.setEnabled(true);
        categoriaText.setEnabled(true);
        disponibilidadeBotao.setEnabled(true);
        
        excluirBotao.setVisible(false);
        editarBotao.setVisible(false);
        salvarBotao.setVisible(false);
        cadastrarBotao.setVisible(true);
        
        anoText.setText("");
        quilometragemText.setText("");
        disponibilidadeBotao.setSelected(true);
    }
    
    public void modoEdicao(){
        placaText.setEnabled(false);
        marcaText.setEnabled(true);
        modeloText.setEnabled(true);
        anoText.setEnabled(true);
        corText.setEnabled(true);
        quilometragemText.setEnabled(true);
        categoriaText.setEnabled(true);
        disponibilidadeBotao.setEnabled(true);
        
        excluirBotao.setVisible(true);
        editarBotao.setVisible(false);
        salvarBotao.setVisible(true);
        cadastrarBotao.setVisible(false);
        
        disponibilidadeBotao.setSelected(veiculo.isDisponibilidade());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoText;
    private javax.swing.JToggleButton cadastrarBotao;
    private javax.swing.JTextField categoriaText;
    private javax.swing.JTextField corText;
    private javax.swing.JToggleButton disponibilidadeBotao;
    private javax.swing.JButton editarBotao;
    private javax.swing.JToggleButton excluirBotao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField marcaText;
    private javax.swing.JTextField modeloText;
    private javax.swing.JTextField placaText;
    private javax.swing.JTextField quilometragemText;
    private javax.swing.JToggleButton salvarBotao;
    // End of variables declaration//GEN-END:variables

}
